CREATE TABLE MTGCard (
  cardId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (cardId) USING BTREE,
  layout VARCHAR(30),
  name VARCHAR(150) NOT NUll,
  namesString VARCHAR(100),
  manaCost VARCHAR(100),
  cmc INT(4) UNSIGNED,
  colorsString VARCHAR(100),
  type VARCHAR(100),
  supertypesString VARCHAR(200),
  typesString VARCHAR(200),
  subtypesString VARCHAR(200),
  rarity VARCHAR(30),
  text VARCHAR(1000),
  flavor VARCHAR(500),
  artist VARCHAR(50),
  number VARCHAR(10),
  power VARCHAR(10),
  toughness VARCHAR(10),
  loyalty INT(4),
  multiverseid INT(10) UNSIGNED,
  variationsString VARCHAR(100),
  imageName VARCHAR(100),
  border VARCHAR(30),
  watermark VARCHAR(30), 
  setCode VARCHAR(10),
  setName VARCHAR(100)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
commit;